### ISSUE TITLE
Driver not found when using pgsql

### ISSUE THREAD

**Issue by marciowinicius** [ambientum/ambientum#125]
This is the error
```
Illuminate\Database\QueryException  : could not find driver (SQL: insert into
 "leilao"."lance" ("cliente", "lote", "valor", "situacao", "dataCadastro", "leil
ao", "apelido", "ambiente") values (50144024, 1816, 7000.00, Recebido, 2019-05-0
7 15:55:51, 9, Jean Carvalho, Teste) returning "id")

```

This is my docker-compose
```
postgres:
    image: tuliogoiania/postgresqlbr
    container_name: leilo-master-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.2-nginx
    container_name: leilo-master-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
    depends_on:
      - postgres
```
